drop table ForexHistoric;
drop table ForexCurrent;

CREATE TABLE ForexHistoric (
  id INT PRIMARY KEY,
  "Date" DATE,
  "AUD" DECIMAL,
  "EUR" DECIMAL,
  "NZD" DECIMAL,
  "GPB" DECIMAL,
  "BRL" DECIMAL,
  "CAD" DECIMAL,
  "CNY" DECIMAL,
  "HKD" DECIMAL,
  "INR" DECIMAL,
  "KRW" DECIMAL,
  "MXN" DECIMAL,
  "ZAR" DECIMAL,
  "SGD" DECIMAL,
  "DKK" DECIMAL,
  "JPY" DECIMAL,
  "MYR" DECIMAL,
  "NOK" DECIMAL,
  "SEK" DECIMAL,
  "GBP" DECIMAL,
  "LKR" DECIMAL,
  "CHF" DECIMAL,
  "TWD" DECIMAL,
  "THB" DECIMAL
);

CREATE TABLE ForexCurrent (
  id INT PRIMARY KEY,
  "Date" DATE,
  "AUD" DECIMAL,
  "EUR" DECIMAL,
  "NZD" DECIMAL,
  "GPB" DECIMAL,
  "BRL" DECIMAL,
  "CAD" DECIMAL,
  "CNY" DECIMAL,
  "HKD" DECIMAL,
  "INR" DECIMAL,
  "KRW" DECIMAL,
  "MXN" DECIMAL,
  "ZAR" DECIMAL,
  "SGD" DECIMAL,
  "DKK" DECIMAL,
  "JPY" DECIMAL,
  "MYR" DECIMAL,
  "NOK" DECIMAL,
  "SEK" DECIMAL,
  "GBP" DECIMAL,
  "LKR" DECIMAL,
  "CHF" DECIMAL,
  "TWD" DECIMAL,
  "THB" DECIMAL
);

SELECT * FROM ForexHistoric;

SELECT * FROM ForexCurrent;
